@extends('web.layout')

@section('main')
<div class="deposit-header">
    <h5>Promotion Description</h5>
    <div class="deposit-back">

          <a onclick="javascript:history.go(-1)">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
            <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0m3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z" />
        </svg>
        </a>
    </div>
</div>
   <div class='container text-center'>
            <div class='row'>
                <div class="Box col-md-6 col-lg-12">
                    <div class="mt-3 text-start">
                        <img src='../IMG/Promo.png' class='w-100' alt='' />
                        <p class='fw-bold pt-3'>About deposit</p>
                        <p>Sales-Ranking Assistant allows members to earn rewards <br /> by inviting friends and family
                            to join. Provide a unique <br /> invitation code for others, allowing them to receive <br />
                            additional rewards from the invitees' first deposit.</p>
                        <p class='fw-bold'>Invitation qualifications</p>
                        <p>• The inviter must be a member of the Sales-Ranking Assistant platform</p>
                        <p>• Inviters must fully comply with all terms and conditions <br /> in order to participate in
                            the Sales-Ranking Assistant <br /> agency cooperation program</p>
                        <p class='fw-bold'>Basic information</p>
                        <p>When relatives and friends use your invitation code to <br /> register for a Sales-Ranking
                            Assistant account, it means <br /> that you have participated in the Sales-Ranking Assistant
                            <br /> agency cooperation program, and that you fully and <br /> unconditionally agree to
                            these terms and conditions, <br /> as well as the decision and interpretation of
                            Sales-Ranking <br /> Assistant . These decisions and interpretations are final <br /> and
                            binding on all matters relating to the plan.</p>
                        <p class='fw-bold'>Reward Method</p>
                        <p>• The reward depends on the first deposit amount of the <br /> invited relatives and friends,
                            and the relative position of <br /> the invitees in the agency program determines the <br />
                            rewards you can get.</p>
                        <img src='../IMG/Promot.png' class='w-75' alt='' />
                        <p class='fw-bold'>Remark</p>
                        <p>1. All personal bonuses generated by participating in the <br /> Sales-Ranking Assistant
                            promotion program are paid by <br /> Sales-Ranking Assistant and will not affect the
                            member's <br /> income.</p>
                        <p>2. Every invitee's first deposit, regardless of the amount, <br /> will be calculated as a
                            reward according to the deposit <br /> amount and will be automatically distributed by the
                            <br /> system.</p>
                        <img src='../IMG/Promot2.png' class='w-75' alt='' />
                        <p>For each invitee's (D) first deposit, the <br /> immediate superior agent (C) receives an
                            <br /> 12% bonus on the amount deposited, and <br /> the two tiers (if any) of agents
                            further up <br /> receive a 6% and 3% bonus in that order, <br /> up to a maximum of three
                            tiers.</p>
                        <p class='fw-bold'>Disclaimer</p>
                        <p>• The Commission and reward obtained by the invited <br /> members will be distributed to the
                            account of the inviter <br /> every day. Inviters can view the commissions and rewards
                            <br /> in fund details.</p>
                        <p>• The terms and conditions contained herein may be <br /> changed or modified at any time.
                            Your continued <br /> participation in the program means that you accept any <br /> changes
                            or modifications to these terms and conditions.</p>
                        <p>• In case of fraud or other related behaviors, including but <br /> not limited to the above
                            examples, Sales-Ranking <br /> Assistant reserves the right to warn or freeze your account.
                        </p>
                        <p>• The agency cooperation plan of Sales-Ranking Assistant <br /> is operated by Sales-Ranking
                            Assistant , and the final <br /> interpretation right belongs to Sales-Ranking Assistant .
                        </p>
                    </div>
                </div>
            </div>
        </div>
      
@endsection
